version: "3.7"
volumes:
  db-store:
  php-fpm-socket:
services:
  https-portal:
    container_name: laravel-https
    image: steveltn/https-portal:1
    ports:
      - '10080:80'
      - '10443:443'
    environment:
      STAGE: local
      DOMAINS: "localhost -> http://web"
    volumes:
      - ./docker/https-portal/cert:/var/lib/https-portal
    depends_on:
      - web

  app:
    container_name: laravel-app
    build: ./docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/opt/laravel-architecture-sample

  web:
    container_name: laravel-web
    build: ./docker/nginx
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/opt/laravel-architecture-sample

  db:
    container_name: laravel-db
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
    ports:
      - 23306:3306
